{
  "config": {
    "step": {
      "user": {
        "data": {
          "url": "[%key:common::config_flow::data::url%]",
          "api_token": "[%key:common::config_flow::data::api_token%]",
          "verify_ssl": "[%key:common::config_flow::data::verify_ssl%]"
        },
        "data_description": {
          "url": "The URL, including the port, of your Portainer instance",
          "api_token": "The API access token for authenticating with Portainer",
          "verify_ssl": "Whether to verify SSL certificates. Disable only if you have a self-signed certificate"
        },
        "description": "You can create an access token in the Portainer UI. Go to **My account > Access tokens** and select **Add access token**"
      },
      "reauth_confirm": {
        "data": {
          "api_token": "[%key:common::config_flow::data::api_token%]"
        },
        "data_description": {
          "api_token": "The new API access token for authenticating with Portainer"
        },
        "description": "The access token for your Portainer instance needs to be re-authenticated. You can create a new access token in the Portainer UI. Go to **My account > Access tokens** and select **Add access token**"
      }
    },
    "error": {
      "cannot_connect": "[%key:common::config_flow::error::cannot_connect%]",
      "timeout_connect": "[%key:common::config_flow::error::timeout_connect%]",
      "invalid_auth": "[%key:common::config_flow::error::invalid_auth%]",
      "unknown": "[%key:common::config_flow::error::unknown%]"
    },
    "abort": {
      "already_configured": "[%key:common::config_flow::abort::already_configured_device%]",
      "reauth_successful": "[%key:common::config_flow::abort::reauth_successful%]"
    }
  },
  "device": {
    "unknown_container": {
      "name": "Unknown container"
    }
  },
  "entity": {
    "binary_sensor": {
      "status": {
        "name": "Status"
      }
    }
  },
  "exceptions": {
    "cannot_connect": {
      "message": "An error occurred while trying to connect to the Portainer instance: {error}"
    },
    "invalid_auth": {
      "message": "An error occurred while trying to authenticate: {error}"
    },
    "timeout_connect": {
      "message": "A timeout occurred while trying to connect to the Portainer instance: {error}"
    }
  }
}
